{-# LANGUAGE OverloadedStrings #-}
module HostSink.Format
  (
    hostFileFMT
  , unboundFMT
  ) where

import           Data.List
import           Data.Text (Text)
import qualified Data.Text as T

hostFileFMT, unboundFMT :: [Text] -> Text
header :: Text
header = "# Autogenerated by host-sink"
hostFileFMT =
  foldl'
    (\t h -> T.concat [t,"\n",T.append "0.0.0.0 " h])
    header

unboundFMT =
  foldl'
    (\t h -> T.concat [t,"\nlocal-data: \"",T.append h " A 0.0.0.0\""])
    header
